marinade-finance/validator-bonds

- package.json
- packages/validator-bonds-cli/__tests__/test-validator/merge.spec.ts
- packages/validator-bonds-cli/package.json
- packages/validator-bonds-sdk/__tests__/bankrun/bankrun.ts
- packages/validator-bonds-sdk/__tests__/bankrun/claimWithdrawRequest.spec.ts
- packages/validator-bonds-sdk/__tests__/bankrun/fundBond.spec.ts
- packages/validator-bonds-sdk/__tests__/utils/staking.ts
- packages/validator-bonds-sdk/__tests__/utils/testTransactions.ts
- packages/validator-bonds-sdk/generated/validator_bonds.ts
- packages/validator-bonds-sdk/package.json
- packages/validator-bonds-sdk/src/instructions/claimWithdrawRequest.ts
- pnpm-lock.yaml
- programs/validator-bonds/src/checks.rs
- programs/validator-bonds/src/error.rs
- programs/validator-bonds/src/instructions/bond/fund_bond.rs
- programs/validator-bonds/src/instructions/settlement/fund_settlement.rs
- programs/validator-bonds/src/instructions/withdraw/claim_withdraw_request.rs
Fixes for `claim_withdraw_request` instruction and adding tests.
> [sdk] claim withdraw request - contract fixes & testing

- .github/workflows/typescript-lint.yml
- api/src/repositories/bond.rs
- common-rs/src/bonds.rs
- common-rs/src/constants.rs
- common-rs/src/funded_bonds.rs
- common-rs/src/lib.rs
- common-rs/src/settlements.rs
- common-rs/src/stake_accounts.rs
- common-rs/src/utils.rs
- common-rs/src/witdraw_requests.rs
- validator-bonds-cli/src/commands/bonds.rs
Update of common-rs with bonds methods loading data from chain.
> [common-rs] update methods

- .buildkite/init-settlements.yml
- .github/workflows/typescript-lint.yml
Fix in using current dir for uploading artifacts
> [settlemnt-pipelines] fixing current directory usage

- .buildkite/init-settlements.yml
- common-rs/src/stake_accounts.rs
- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
- settlement-pipelines/src/bin/init_settlement.rs
Enriching info messages in pipeline processing. Finding amount of funded from number of stake accounts from chain for any type of funding.
> Pipeline settlement adjust

- .buildkite/claim-settlements.yml
- Cargo.lock
- Cargo.toml
- common-rs/Cargo.toml
- common-rs/src/stake_accounts.rs
- packages/validator-bonds-sdk/__tests__/utils/staking.ts
- programs/validator-bonds/src/instructions/settlement/claim_settlement.rs
- settlement-pipelines/Cargo.toml
- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
- settlement-pipelines/src/bin/claim_settlement.rs
- settlement-pipelines/src/bin/init_settlement.rs
- settlement-pipelines/src/bin/list_claimable_epoch.rs
- settlement-pipelines/src/json_data.rs
- settlement-pipelines/src/lib.rs
- settlement-pipelines/src/settlements.rs
Settlement claiming pipeline. 
~~(Unfortunately, ended up with a spaghetti again. I will need to refactor when all settles.)~~
~~This is untested (at least from base) and I'm creating it as draft with in hope will be finished during tomorrow.~~
> Pipelines settlement claiming

- .buildkite/claim-settlements.yml
- common-rs/src/stake_accounts.rs
- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
- settlement-pipelines/src/bin/claim_settlement.rs
- settlement-pipelines/src/bin/init_settlement.rs
- settlement-pipelines/src/lib.rs
* fix way to find out the deactivated stake accounts
* using loaded stake accounts despite they are not all
* TS test alignments
> [settlement-pipelines] fixes on claiming

- .buildkite/claim-settlements.yml
- .buildkite/close-settlements.yml
- .buildkite/init-settlements.yml
- settlement-pipelines/src/bin/init_settlement.rs
> [settlements-pipeline] adjusting pipeline wallets used for fee&rent

- Cargo.lock
- common-rs/src/lib.rs
- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
- settlement-pipelines/src/anchor.rs
- settlement-pipelines/src/arguments.rs
- settlement-pipelines/src/bin/claim_settlement.rs
- settlement-pipelines/src/bin/close_settlement.rs
- settlement-pipelines/src/bin/init_settlement.rs
Still, there is trouble (warnings) around
```
required for `Arc<DynSigner>` to implement `Send` and `Sync`
```
which could be hopefully fixed by
https://github.com/solana-labs/solana/pull/34984
which was merged in March while not included in `18.x.x` releases (and we use 17.x.x in repo).
I haven't got into details about releases and how it works.
> [pipelines] working with Arc as of async code

- settlement-pipelines/src/bin/init_settlement.rs
When a validator has not got a Bond account but gets some delegated SOLs (it could be e.g. because somebody deposits stake accounts to Marinade) then for a protected event the Settlement cannot be created as no funding at bond exists.
If such a validator makes a bigger issue with processing then part could need to be covered by Marinade and Marinade has to still pay its part despite the validator does not participate by having the Bond account.
When no Bond account exists then Marinade will slowly redelegates the SOLs from the validator without the Bond to some funded validators.
> [pipeline] place info on init when no bond but marinade funding

- .buildkite/claim-settlements.yml
- .buildkite/close-settlements.yml
- .buildkite/init-settlements.yml
- .buildkite/verify-settlements.yml
- common-rs/src/settlements.rs
- packages/validator-bonds-cli/README.md
- programs/validator-bonds/src/instructions/settlement/cancel_settlement.rs
- settlement-pipelines/Cargo.toml
- settlement-pipelines/README.md
- settlement-pipelines/src/bin/verify_settlement.rs
A pipeline that checks about existing Settlements on-chain and compares them with JSON files on gcloud to detect unknown settlements that were not created based on epoch gcloud setup.
That could mean the operator manually creates Settlements which could be a mallicous actor stolen key pairs.
> [pipeline] settlement pipeline to check unknown Settlement on-chain

- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
Fixes in tests based on the changes in pipeline processing where funding was separated to its own "cli" command.
> [pipeline] fix tests for additional funding step

- settlement-engine/src/protected_events.rs
- snapshot-parser/Cargo.toml
- snapshot-parser/src/bin/cli.rs
- snapshot-parser/src/validator_meta.rs
Adding jito mev commission field for validators json.
> [snapshot-parser] obtaining jito mev comission

- settlement-pipelines/src/stake_accounts.rs
Change priority for stake accounts taken for claiming into with liquid staker authority.
Some refactorings are part of the PR as considered some bad naming here around.
> [pipelines] liquid staker hot fix

- .buildkite/prepare-protected-events.yml
Fix for a copypasta error in buildkite pipeline processing :sweat:
> [buildkite] fix prepare protected events epoch get

- jest.config.test-validator.js
- package.json
- packages/validator-bonds-cli/__tests__/test-validator/configureConfig.spec.ts
- packages/validator-bonds-sdk/__tests__/bankrun/fundSettlement.spec.ts
- settlement-pipelines/src/bin/fund_settlement.rs
Few fixes on tests and reporting of pipeline fund settlement.
> [tests] fix + stabilize

- packages/validator-bonds-cli/README.md
A slight doc update regarding the withdraw request functionality.
> [readme][cli] update withdraw request info

- Cargo.lock
- Cargo.toml
- settlement-pipelines/src/bin/fund_settlement.rs
- settlement-pipelines/src/executor.rs
- settlement-pipelines/src/reporting.rs
Depending on passing PR https://github.com/marinade-finance/solana-transaction-builder/pull/6
> [pipeline] seq executor run one by one with error returning

- README.md
- programs/validator-bonds/ON_CHAIN_ANALYSIS.md
Adding doc with flipside queries to check the historical tx data.
> [readme] adding a doc on flipside queries

- README.md
Small readme update to help in deploying the programs.
@Cerbah asking for the review check.
> [readme] update of readme about deployment of contract

- snapshot-parser/src/jito_mev.rs
> [parser] fix epoch number logged

- README.md
Updating README with a way to upload info about the project to OtterSec API to be considered as Verified Build
https://explorer.solana.com/address/vBoNdEvzMrSai7is21XgVYik65mqtaKXuSdMBJ1xkW4/verified-build
> [readme] add info how to create verifiable build

- common-rs/src/utils.rs
- settlement-pipelines/src/bin/init_settlement.rs
It happens from time to time that the init settlement pipeline reports and error that there is not existing `SettlemntClaim` account associated with the created `Settlement`. When on checks if the account does not exist then he finds there is one created without any issue (especially when init settlement instruction creates settlement and settlementclaim in one go).
The issue seems to be an "RPC" data loading trouble and this update tries to fix this by retrying to get data again when not found at all (despite expecting they should be found).
```
[... ERROR settlement_pipelines::reporting] CRITICAL [upsize_settlements]: No SettlementClaims account B8MjvXcDTyxgyCEscBgVNqu5nrBstSuBdvQhu85HJCaW for an existing Settlement ApW1JJEh1k4JTvjQcCog9uyNW6oq2bVvXCHYmN9pRNo5
```
> [pipelines] init settlement fails to load created accounts from chain, trying to address the issue

- packages/validator-bonds-cli/README.md
Fix the readme to link correctly the section + spelling "cancelling" in the British way.
> [readme] update cli readme of correct link to cancel withdraw request

- Trident.toml
- trident-tests/README.md
- trident-tests/fuzz_tests/fuzz_0/common.rs
- trident-tests/fuzz_tests/fuzz_0/fuzz_instructions.rs
* fix of `UpsizeSettlementClaims` test instruction
* adding a bit more info on troubleshooting to README
> Fuzz testing fixes

- .buildkite/claim-settlements.yml
- .buildkite/close-settlements.yml
- .buildkite/fund-settlements.yml
- .buildkite/init-settlements.yml
- .buildkite/verify-settlements.yml
- scripts/execute-handlers.sh
- settlement-pipelines/src/bin/claim_settlement.rs
- settlement-pipelines/src/bin/fund_settlement.rs
- settlement-pipelines/src/bin/init_settlement.rs
- settlement-pipelines/src/bin/verify_settlement.rs
- settlement-pipelines/src/cli_result.rs
- settlement-pipelines/src/json_data.rs
- settlement-pipelines/src/reporting.rs
- settlement-pipelines/src/settlements.rs
Add warning error handling that won't fail the pipeline but it reports them to a report data.
> [pipeline] working with warnings when no stake account exists

- packages/validator-bonds-cli/src/commands/manage/configureConfig.ts
- packages/validator-bonds-cli/src/commands/show.ts
- scripts/execute-handlers.sh
An adjustment of code comment and bonds CLI
> Pipeline doc fix

- packages/validator-bonds-cli/README.md
- packages/validator-bonds-cli/src/commands/manage/claimWithdrawRequest.ts
A small change on CLI helps the text to be a bit clearer.
(this change comes from a discussion with copycat while this change is just a minor enhancement)
> [cli] claim withdraw request with better help text

- CHANGELOG.md
- package.json
- packages/validator-bonds-cli-core/package.json
- packages/validator-bonds-cli-institutional/README.md
- packages/validator-bonds-cli-institutional/package.json
- packages/validator-bonds-cli-institutional/src/index.ts
- packages/validator-bonds-cli/README.md
- packages/validator-bonds-cli/package.json
- packages/validator-bonds-cli/src/index.ts
- packages/validator-bonds-sdk/package.json
- pnpm-lock.yaml
- settlement-pipelines/package.json
I did a wrong publish of npm package. I believe it was caused by the fact of not re-building the old version of the package on my local system. That's why I changed the package.json script and needed a double update of versions.
> Version bumps and fixing script for publish

- packages/validator-bonds-cli/README.md
Based on feedback from a support ticket is needed to elaborate on claiming withdrawal request from Bond.
> [readme] update readme info about withdrawal from bonds

- packages/validator-bonds-cli/README.md
- programs/validator-bonds/ON_CHAIN_ANALYSIS.md
I did some investigation with flipside queries and updated the readme with a small update.
> [readme] small update on onchain flipside analysis

- .buildkite/claim-settlements.yml
- .buildkite/close-settlements.yml
- .buildkite/copy-parsed-snapshot.yml
- .buildkite/fund-settlements.yml
- .buildkite/init-settlements.yml
- .buildkite/prepare-bid-distribution.yml
- .buildkite/prepare-bid-psr-distribution.yml
- .buildkite/prepare-institutional-distribution.yml
- scripts/execute-handlers.sh
Still not clear if better way to work with this
https://forum.buildkite.community/t/best-practices-for-handling-redacted-vars-in-buildkite-pipelines/4314/3
> [buildkite] fixing issues with redacted vars

- settlement-pipelines/src/bin/fund_settlement.rs
- settlement-pipelines/src/bin/init_settlement.rs
- settlement-pipelines/src/reporting_data.rs
Fixing the Institutional type used for reporting about initialisation and funding settlements in pipeline processing.
> [pipelines] fixing report type for institutional

- .buildkite/scheduler-institutional.yml
Fix a wrong file path to be checked by scheduler to find if epoch was already processed.
> [buildkite] fix institutional scheduler

- settlement-pipelines/src/bin/init_settlement.rs
Fix reporting info for upsize settlement instruction call to not be reported on institutional as a failure.
> [pipeline] adjust reporting for institutional (fix) [GEN-5101]

- .buildkite/claim-settlements.yml
Just a wrongly named the pipeline step (probably a copy&paste error from some past days)
> [pipeline] fix naming [trivial]

- packages/validator-bonds-cli-institutional/README.md
Adding information about bonds API for Select.
> [readme] update info about institutional bonds api [trivial]

- packages/validator-bonds-cli-institutional/README.md
- packages/validator-bonds-cli/README.md
Readme update to clarify how the 'fund-bon-sol' command works.
(had a talk with Cerba, who wonders how that works)
> [readme] adding note on 'fund-bond-sol' command

- .buildkite/prepare-institutional-distribution.yml
- scripts/generate-select-validator-report.bash
Updating report script to show in table amount of validator rewards.
> [pipeline] update report script

- scripts/settlement-json-listing.sh
- settlement-distributions/institutional-distribution/src/institutional_payouts.rs
- settlement-distributions/institutional-distribution/src/settlement_generator.rs
On checking data from calculations I found there is incorrectly considered stake accounts in payouts merging in the settlement listings (not affecting the merkle tree composition).
> [prepare institutional] do not duplicate stake accounts [GEN-5355]

- settlement-distributions/bid-distribution/src/sam_meta.rs
- settlement-distributions/bid-distribution/src/settlement_claims.rs
Revert the last hotfix.  To be merged at epoch 808.
> [trivial] 20250621 hotfix sam meta revert

- .buildkite/fund-settlements.yml
- .buildkite/merge-stakes.yml
- settlement-distributions/institutional-distribution/src/settlement_generator.rs
- settlement-pipelines/Cargo.toml
- settlement-pipelines/src/bin/merge_stakes.rs
- settlement-pipelines/src/stake_accounts.rs
Bonds CLI command to clean up reset stake accounts assigned to a single validator by merging them into one stake account.
> [cli] adding merge cli command [GEN-6180]

- settlement-pipelines/src/bin/merge_stakes.rs
I failed to filter out the transient stake accounts that are not permitted to be merged.
> [pipeline/cli] merge; fixing errors on attempts to merge transient stake [GEN-6180] 
