marinade-finance/validator-bonds

- Cargo.lock
- Cargo.toml
- insurance-engine/src/insurance_claims.rs
- insurance-engine/src/insured_events.rs
- insurance-engine/src/utils.rs
The serde fails[1] to serialize the HashMap that contains non string on key. I was not able to find to force it to use e.g., `to_string()` or smt.
A way I'm coming with is to serialize/deserialize "by hand". I would be happy to learn some more rustacean way.
[1]
```
[2024-02-22T10:35:31Z INFO  insurance_engine_cli] Starting insurance engine...
[2024-02-22T10:35:31Z INFO  insurance_engine_cli] Using whitelist on stake authorities: [stWirqFCf2Uts1JBL1Jsd3r6VBWhgnpdPxCTe1MFjrq, 4bZ6o3eUUNXhKuqjdCnCoPAoLgWiuLYixKaxoa8PpiKk, ex9CfkBZZd6Nv9XdnoDmmB45ymbu4arXVk7g5pWnt3N]
[2024-02-22T10:35:31Z INFO  insurance_engine_cli] Loading validator meta collection...
[2024-02-22T10:35:31Z INFO  insurance_engine_cli] Loading stake meta collection...
[2024-02-22T10:35:46Z INFO  insurance_engine_cli] …
```
> [pubkey in treenode] fix for serialization

- settlement-engine/src/merkle_tree_collection.rs
- settlement-engine/src/protected_events.rs
- settlement-engine/src/settlement_claims.rs
- settlement-engine/src/settlement_config.rs
Using clippy fix and using the recommendation from the warning output. I'm not fully sure about the `&Box<dyn>` but based on the documentation that should be auto de-referenced.
```
warning: you seem to be trying to use `&Box<T>`. Consider using just `&T`
--> settlement-engine/src/settlement_claims.rs:66:29
|
66 |     stake_authority_filter: &Box<dyn Fn(&Pubkey) -> bool>,
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `&dyn Fn(&Pubkey) -> bool`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#borrowed_box
= note: `#[warn(clippy::borrowed_box)]` on by default
warning: you seem to be trying to use `&Box<T>`. Consider using just `&T`
--> settlement-engine/src/settlement_claims.rs:139:29
|
139 | …
```
> [clippy] --fix + warning recommendations

- .buildkite/claim-settlements.yml
- .buildkite/init-settlements.yml
- settlement-pipelines/src/bin/claim_settlement.rs
- settlement-pipelines/src/bin/init_settlement.rs
Init and claim settlements to use different wallets for tx fee payer and rent payer.
For close settlements I assume there will be used the `VALIDATOR_BONDS_MARINADE_TX_FEE_PAYER` to pay for tx fees.
> [settlement-pipeline] rent payer for init and claim

- Cargo.lock
- common-rs/src/stake_accounts.rs
- common-rs/src/utils.rs
- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
- settlement-pipelines/src/bin/claim_settlement.rs
- settlement-pipelines/src/bin/close_settlement.rs
- settlement-pipelines/src/bin/init_settlement.rs
- settlement-pipelines/src/cli_result.rs
- settlement-pipelines/src/reporting.rs
- settlement-pipelines/src/settlements.rs
- settlement-pipelines/src/stake_accounts.rs
The `init_settlement` pipeline started to fail as the pipeline wrongly did not consider the stake account state and was not able to merge in such cases.
The change verifies the stake state and lets only those with the same state merge. If the state differs then it funds the accounts directly without merging beforehand.
Still, the merging is beneficial for claiming we need the best one big account that is just split into parts and not pointing into settlements multiple accounts that need to stay with "overflow" of 1 SOL as being the requirements for the existence of the stake account.
> [pipelines] init to verify funding stake state

- .buildkite/close-settlements.yml
- common-rs/src/stake_accounts.rs
- settlement-pipelines/src/bin/claim_settlement.rs
- settlement-pipelines/src/bin/close_settlement.rs
- settlement-pipelines/src/bin/init_settlement.rs
- settlement-pipelines/src/json_data.rs
- settlement-pipelines/src/lib.rs
- settlement-pipelines/src/settlement_data.rs
For settlement pipelines adding more details on informing what happened on closing settlement.
Up to now, there was just a summary of closed accounts but without more granularity info on what epoch and settlement that was related to.
> [pipelines] adding details on close settlements + merging loading json

- packages/validator-bonds-sdk/__tests__/bankrun/mergeStake.spec.ts
- packages/validator-bonds-sdk/src/instructions/mergeStake.ts
- programs/validator-bonds/src/instructions/stake/merge_stake.rs
The validator bonds on-chain program consists of a flaw of the wrong signature on merging Settlement stake accounts. That issue causes the contract does not permit merging stake accounts that are funded to Settlements (which is completely correct from contract logic).
The contract contains a typo in using the wrong PDA signature where the funded stake account to Settlement has got staker derived from the settlement address whereas the funded stake account to Bond has got staker and withdrawer authorities both the same derived from the config address.
The most important change is in the contract code at:
https://github.com/marinade-finance/validator-bonds/pull/69/files#diff-5d490d7550af02cc23f72b38ddc093fc16eb160721becf5855dfc8190ee0a2ee
(the rest is about testing)
> [contract] merge stake fixing correct signature for merging

- packages/validator-bonds-sdk/__tests__/bankrun/claimSettlement.spec.ts
- packages/validator-bonds-sdk/__tests__/utils/merkleTreeTestData.ts
- programs/validator-bonds/src/instructions/settlement/claim_settlement.rs
- settlement-engine/src/merkle_tree_collection.rs
The current contract does not permit to withdraw exact amount from a stake account when the claim amount matches the number of lamports that is in the stake account.
Currently, the stake account for settlement claiming needs to be charged with `claim amount + minimal size of stake account`. That's completely ok when the `claim amount` is smaller than what's available in the stake account. The claiming is processed and after that, the stake account has to be still valid.
But when we want to have a way to charge a stake account to a settlement with a precise amount and then let it be claimed by someone let's not force overfunding (in logic it's not incorrect as the overfunding will be returned back to the original owner on closing the settlement).
The contract code change is at: …
> [contract] fix for claim settlement on exact match

- common-rs/src/stake_accounts.rs
- packages/validator-bonds-sdk/__tests__/bankrun/bankrun.ts
- packages/validator-bonds-sdk/__tests__/bankrun/claimSettlement.spec.ts
- packages/validator-bonds-sdk/__tests__/bankrun/fundBond.spec.ts
- packages/validator-bonds-sdk/__tests__/utils/testTransactions.ts
- packages/validator-bonds-sdk/generated/validator_bonds.ts
- programs/validator-bonds/src/checks.rs
- programs/validator-bonds/src/error.rs
- programs/validator-bonds/src/instructions/bond/fund_bond.rs
Changing `fund_bond` instruction to permit to funding of any stake account that is:
* delegated 
* non-locked
Before this change, it does matter if it's activating or deactivating etc. It was permitted to get funded only fully activated stake account.
The idea behind the change is to make it easier to fund a bond for validators.
It should be possible to create a stake account and immediately fund it to the bond account without the need to wait a whole epoch to get it activated (as it is for a newly created stake account right now).
The technical presumption of the change is 
* The `fund_bond` changes the `withdraw` and `staker` authorities to a PDA `validator bonds authority` based on the program id and config address.
* The bond-funded stake account can be used to fund the Settlement. …
> [contract] fund makes possible when activating

- .buildkite/claim-settlements.yml
- .buildkite/close-settlements.yml
- .buildkite/fund-settlements.yml
- settlement-pipelines/src/lib.rs
- settlement-pipelines/src/settlements.rs
Old and new merkle trees (contract v1 vs contract v2 containing index) are incompatible and JSON fails to be loaded.
The YAML pipeline "fix" skips the old epochs and working only with new ones.
> [pipelines] for contract v2 skipping old merkle trees

- packages/validator-bonds-sdk/__tests__/bankrun/fundSettlement.spec.ts
- packages/validator-bonds-sdk/__tests__/utils/staking.ts
Adding tests that check the behaviour of `fund_settlement` instruction for stake account that is mostly delegated to a validator but there is some SOL that's not delegated (expected that it may happen e.g., for validators that gets MEV rewards as direct transfer of SOLs into stake account, that part of SOL is not delegated).
When such a stake account is used for (part delegated, part - smaller to 1 SOL - is not-delegated) funding a `Settlement` then the stake account will be assigned with non-delegated SOLs and then the rest will be the delegated SOLs.
This as well means that MEV rewards are just used for paying for Settlement creation and there is not a big need for any special redelegation instruction.
> [contract&test] test for fund_settlement usage of un-delegated SOLs in stake account

- snapshot-parser/src/validator_meta.rs
I had pretty wrong expectations. The mev is defined for the current epoch and thus it can be checked. I could see the prior epoch taken in other parsing parts, but when working with snapshot it seemed to me different.
The code in this PR works fine.
Is it ok to check the epoch for the jito tip distribution account this way?
> [snapshot-parser] fix jito mev commission epoch check

- .buildkite/claim-settlements.yml
- protected-event-distribution/src/protected_events.rs
- protected-event-distribution/src/settlement_config.rs
- scripts/generate-discord-public-report.bash
- settlement-config.yaml
I found an issue around backwards compatibility and the ability to work with old JSON data within the project.
The closing, funding etc. needs to be able to work with old and new data (I started to use v1 - not with sam and v2 - with some, but if there is better naming please propose)
With that the protected event of new name is `CommissionSamIncrease` and placing back the other types of protected events from v1.
> Non sam events compatibity fix

- .buildkite/prepare-protected-events.yml
- protected-event-distribution/src/protected_events.rs
- protected-event-distribution/src/revenue_expectation_meta.rs
- scripts/generate-discord-public-report.bash
Using non bid commission increase value from `ds-sam` to evaluate commission increase not covered by bidding.
This depends on PR: https://github.com/marinade-finance/ds-sam/pull/7
> [protected events] evaluate commission increase not covered by bidding

- protected-event-distribution/src/settlement_claims.rs
- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
- settlement-pipelines/src/bin/fund_settlement.rs
- settlement-pipelines/src/json_data.rs
- settlement-pipelines/src/settlement_data.rs
- settlement-pipelines/src/stake_accounts.rs
The PR covers small refactoring of naming, adding a little bit of logging info for the fund pipeline to have better insight into what happened and mostly fixes an issue of failing pipeline on funding when the same stake account could be taken for two different settlement of the same vote account.  As for wrong calculation in the pipeline, it could happen that after funding there is not enough left for the financing of the other. When both such fundings are placed into the same transaction the transaction fails and nothing is funded.
The issue fix is the change of the if statement
https://github.com/marinade-finance/validator-bonds/compare/pipelines-more-info-logging?expand=1#diff-ed4510b215e1a2a295acd1b99614e0b3b95c79d5fcea050225b08cd2afcad716L400
> Fix for funding bin cli pipeline

- .buildkite/fund-settlements.yml
- .buildkite/init-settlements.yml
- .buildkite/prepare-bidding.yml
- .buildkite/prepare-protected-events.yml
Two things adjusted here:
1. Prepare bidding/protected-events pipeline to fund only newly created settlements (avoiding race conditions on not existing settlements from in parallel running pipeline of the other type)
2. PSR feed is updated only after initialization is executed (not immediately after JSON data is created and not before an operator manually permits init settlement processing)
> Adjusting buildkite pipelines

- .buildkite/claim-settlements.yml
- .buildkite/fund-settlements.yml
- .buildkite/init-settlements.yml
I made an error in processing buildkite metadata processing. It works with init settlement but I forgot to check the claiming.
https://buildkite.com/docs/agent/v3/cli-meta-data#setting-data-description
```
buildkite-agent meta-data set <key> [value] [options...]
Set arbitrary data on a build using a basic key/value store.
You can supply the value as an argument to the command, or pipe in a file or script output.
```
and **!**
```
The value must be a non-empty string, and strings containing only whitespace characters are not allowed.
```
Follow-up to #96
> [pipelines] fix wrong claim type for funding pipelinel

- scripts/settlement-json-listing.sh
At start of init settlement pipeline the script is used to list (and check) the JSON data. Purpose of this PR is to get the processing a way faster than it's now (from 10s of minutes to ~3 minutes).
> [scripts] speeding up script processing

- .buildkite/claim-settlements.yml
- .buildkite/close-settlements.yml
- .buildkite/fetch-and-parse-snapshot.yml
- .buildkite/fund-settlements.yml
- .buildkite/init-settlements.yml
- .buildkite/prepare-bidding.yml
- .buildkite/prepare-protected-events.yml
- packages/validator-bonds-cli/__tests__/test-validator/show.spec.ts
- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
- settlement-pipelines/src/bin/claim_settlement.rs
- settlement-pipelines/src/bin/close_settlement.rs
- settlement-pipelines/src/bin/fund_settlement.rs
- settlement-pipelines/src/bin/init_settlement.rs
- settlement-pipelines/src/lib.rs
- settlement-pipelines/src/reporting_data.rs
- settlement-pipelines/src/settlement_data.rs
Adding better reporting data from on-chain pipeline bonds processing.
It won't be perfect, but it's a step to enhance the current state.
------------------------------------
Funding **FROM**
```
Epoch 664 funded 0/77 settlements with 0/320.694193201 SOLs (before this already funded 77/77 settlements with 320.694193201/320.694193201 SOLs)
```
**TO**
```
Epoch 664 funded 0/77 settlements with 0/320.694193201 SOLs (before this already funded 77/77 settlements with 320.694193201/320.694193201 SOLs)
- Bidding: funded 0/73 settlements with 0/316.622360817 SOLs (before this already funded 73/73 settlements with 316.622360817/316.622360817 SOLs)
- Protected Events: funded 0/4 settlements with 0/4.071832384 SOLs (before this already funded 4/4 settlements with 4.071832384/4.071832384 SOLs)
``` …
> Pipeline better fund claim reporting

- .buildkite/fund-settlements.yml
- settlement-pipelines/src/bin/claim_settlement.rs
- settlement-pipelines/src/executor.rs
Pipelines
* Fixing an error on uploading artifacts to gcloud from funding 
* Decreasing parallelism for claiming from 300 in parallel to 30 (tested that default 100 is still too much) to not getting many `429` errors
> Decrease parallel execution speed

- packages/validator-bonds-sdk/src/instructions/configureConfig.ts
I found an error in configure instruction SDK that does not permit to define value `0`.
> [cli] fix for configure init value being 0

- packages/validator-bonds-sdk/__tests__/bankrun/fundSettlement.spec.ts
Fix the `fundSettlement` test that does not work when defining a different configuration for a minimum stake[1].
By default, we have defined 1 SOL as we thought the feature flag `9onWzzvCzNC2jfhxxeqRgs5q7nFAAKpCUvkj6T6GJK9i`/`Raise minimum stake delegation to 1.0 SOL #24357`  will be activated but it seems it's not in the short term planned for Solana. So I tried to run the tests with the value of `0` and two tests failed as there was a hardcoded expectation to work with 1 SOL as minimum.
This change fixes that value being hardcoded in the test.
```
await executeConfigureConfigInstruction({
program,
provider,
configAccount,
adminAuthority,
// no minimum amount to work with stake accounts when splitting (e.g., fund settlement)
newMinimumStakeLamports: 0,
})
```
> [tests] fix hardcoded 1 SOL in tests; failing when init minimumStakeLamports is defined

- settlement-pipelines/src/bin/fund_settlement.rs
- settlement-pipelines/src/reporting_data.rs
`fund-settlement` reports wrong data about the number of already funded settlements. The calculation (filter) was done wrongly and those settlements that were not funded were summed to ones that were funded with some value.
> [pipelines] fix fund pipeline reporting

- packages/validator-bonds-sdk/__tests__/bankrun/fundSettlement.spec.ts
- packages/validator-bonds-sdk/generated/validator_bonds.ts
- packages/validator-bonds-sdk/src/instructions/fundSettlement.ts
- programs/validator-bonds/src/instructions/settlement/fund_settlement.rs
- settlement-pipelines/src/bin/fund_settlement.rs
Currently when one tries to fund the Settlement with a stake account containing the larger amount of non-delegated lamports (bigger to funded amount + stake account rent) then the instruction fails.
It's because the stake program `split` instruction places all non-delegate lamports into the origin stake account and the rest is moved into a split. If the amount of non-delegated lamports is so many that the original stake account won't be a valid delegated stake account (a valid stake account needs to have delegated to a minimum of 1 SOL, at least per expected feature gate) then it ends failing.
I do propose a PR to fix the issue of funding Settlements with non-delegated lamports (when more of them available in a stake account).
But I'm not fully happy with the current result. I realized I …
> [contract] fund settlement with non-delegated lamports

- packages/validator-bonds-cli/src/commands/show.ts
Updating CLI of validator bonds to parse and show event data processed from CPI anchor calls.
> [cli] parsing anchor cpi event data not only simple event data

- CHANGELOG.md
- Cargo.lock
- packages/validator-bonds-sdk/__tests__/bankrun/fundSettlement.spec.ts
- packages/validator-bonds-sdk/generated/validator_bonds.ts
- packages/validator-bonds-sdk/src/instructions/fundSettlement.ts
- programs/validator-bonds/Cargo.toml
- programs/validator-bonds/src/instructions/settlement/fund_settlement.rs
- resources/idl/validator_bonds.json
- settlement-pipelines/src/bin/fund_settlement.rs
Update the `main` branch from the https://github.com/marinade-finance/validator-bonds/tree/contract-v2.1.0-deploy that is the branch with program deployed on-chain. Plus adding changelog and idl updates related to the contract release.
> Contract v2.1.0 deploy update main

- packages/validator-bonds-cli/src/commands/manage/fundBond.ts
- packages/validator-bonds-cli/src/commands/manage/initBond.ts
- packages/validator-bonds-cli/src/commands/manage/initWithdrawRequest.ts
- packages/validator-bonds-cli/src/commands/show.ts
- packages/validator-bonds-cli/src/commands/utils.ts
When user wants to create a bonds or withdraw request via CLI and such account exists, it should be just info and not an error.
> [cli] handle errors when bond or withdraw request exists on chain

- packages/validator-bonds-cli/src/commands/utils.ts
- packages/validator-bonds-sdk/src/orchestrators/orchestrateWithdrawRequest.ts
Users often try to withdraw bonds not with the address of the bond or withdrawal request but (kind of logically) with the address of a stake account. This adjustment will check if the address is a stake account and derive a vote account from it that can eventually be used for the withdrawal of the bond.
> [cli] make withdraw claim to work with stake accounts

- Anchor.toml
Aligning `Anchor.toml`  Solana version to 1.17.x as the all dependencies are specified in `Cargo.toml` workspace.
> [dependency] Anchor toml to use solana 1.17.22 as Cargo.toml

- common-rs/src/utils_rpc_retry.rs
- settlement-pipelines/src/bin/init_settlement.rs
Enhancing the retry rpc functionality to have a chance to force all pub keys are expected to have a record onchain. This is follow-up to https://github.com/marinade-finance/validator-bonds/pull/151
> [rpc retry] adding functionality to retry until all pubkeys are fetched

- .buildkite/claim-settlements.yml
Because of a wrong identifier of `depends_on` the claim bond pipeline fails always :shrug:
> [buildkite] fix depends on for claim pipeline to not fail

- settlement-pipelines/src/bin/fund_settlement.rs
- settlement-pipelines/src/stake_accounts.rs
The perspective of this change is to re-define the way stake accounts are considered for funding-created settlements.
Up to now (with the context of having the issue in the contract for some time until October 2024 - https://github.com/marinade-finance/validator-bonds/pull/77) the funding pipeline was taking the biggest stake account to be used for funding the settlement.
This change prioritised using the stake accounts with the biggest part of undelegated lamports. Those can be directly used for claiming the settlements while the split part is left delegated and not claimed.
> [pipelines] using stake accounts with biggest non-delegated part first on settlement funding

- packages/validator-bonds-cli/README.md
- pnpm-lock.yaml
- scripts/update-cli-version.sh
On publishing the CLI version 2.0.5 I forgot to include the pnpm-lock.yaml into repository. Can you @martinkrecek approve the PR to involve that, please?
> [pnpm.lock] update with version 2.0.5

- .buildkite/prepare-bidding.yml
A small update on prepare bidding pipeline to fail when no SAM data is received (i.e., the array is empty as for any unknown epoch `curl  "https://scoring.marinade.finance/api/v1/scores/sam?epoch=1000000"` the result is `[]`.
> [pipeline] fail when no sam data available

- package.json
- packages/validator-bonds-cli/package.json
- packages/validator-bonds-sdk/__tests__/bankrun/cancelWithdrawRequest.spec.ts
- packages/validator-bonds-sdk/__tests__/bankrun/claimWithdrawRequest.spec.ts
- packages/validator-bonds-sdk/__tests__/bankrun/fundBond.spec.ts
- packages/validator-bonds-sdk/__tests__/bankrun/initSettlement.spec.ts
- packages/validator-bonds-sdk/__tests__/bankrun/initWithdrawRequest.spec.ts
- packages/validator-bonds-sdk/__tests__/bankrun/mergeStake.spec.ts
- packages/validator-bonds-sdk/__tests__/test-validator/apiStakeAccount.spec.ts
- packages/validator-bonds-sdk/__tests__/test-validator/initSettlement.spec.ts
- packages/validator-bonds-sdk/__tests__/test-validator/initWithdrawRequest.spec.ts
- packages/validator-bonds-sdk/__tests__/utils/helpers.ts
- packages/validator-bonds-sdk/__tests__/utils/testTransactions.ts
- pnpm-lock.yaml
- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
Fixing some of the dependabot security warnings for typescript.
This PR is a follow-up to https://github.com/marinade-finance/validator-bonds/pull/168
(what is relevant to this PR is the `[security] ...` commit)
> Security vulnerabilities report fix

- CHANGELOG.md
- packages/validator-bonds-cli-core/package.json
- packages/validator-bonds-cli-core/src/commands/manage/configureBond.ts
- packages/validator-bonds-cli-core/src/commands/manage/initBond.ts
- packages/validator-bonds-cli-institutional/README.md
- packages/validator-bonds-cli-institutional/__tests__/test-validator/configureBondInstitutional.spec.ts
- packages/validator-bonds-cli-institutional/__tests__/test-validator/initBondInstitutional.spec.ts
- packages/validator-bonds-cli-institutional/package.json
- packages/validator-bonds-cli-institutional/src/commands/manage/configureBond.ts
- packages/validator-bonds-cli-institutional/src/commands/manage/initBond.ts
- packages/validator-bonds-cli-institutional/src/index.ts
- packages/validator-bonds-cli/README.md
- packages/validator-bonds-cli/__tests__/test-validator/configureBond.spec.ts
- packages/validator-bonds-cli/__tests__/test-validator/initBond.spec.ts
- packages/validator-bonds-cli/__tests__/test-validator/show.spec.ts
- packages/validator-bonds-cli/package.json
- packages/validator-bonds-cli/src/commands/manage/configureBond.ts
- packages/validator-bonds-cli/src/commands/manage/initBond.ts
- packages/validator-bonds-cli/src/commands/show.ts
- packages/validator-bonds-cli/src/index.ts
- packages/validator-bonds-sdk/package.json
- packages/validator-bonds-sdk/src/instructions/initBond.ts
- pnpm-lock.yaml
- settlement-pipelines/package.json
Implementing MIP.10 proposal
* https://forum.marinade.finance/t/mip-10-simplification-of-sams-delegation-strategy/1713
* https://app.realms.today/dao/MNDE/proposal/E5HsJzBZhniUfoRrT7aV1gAJ2VXqFQqvwWp8AcgSco9i
Removal of max stake wanted from the CLI (configure, show, readme)
Notes:
* The existence of the commented-out text for the CLI arguments is intentional. The contract still supports this configuration option and maybe later it can be added back. While it seems wrong from a review perspective I'm not such strong in this opinion.
* the dependencies update works for the local development. For publishing there needs to be added a new commit without `workspace:`.
> [MIP.10] removal of stake wanted, increase TVL cap to 4%

- settlement-distributions/bid-distribution/src/settlement_claims.rs
A missed configuration of max_stake_wanted has to be omitted on bid preparation.
> [MIP.10] fixing claim preparation withouth max stake wanted

- settlement-config.yaml
- settlement-pipelines/src/bin/fund_settlement.rs
There are two TODO items in validator bonds code base that I believe are not up-to-date anymore.
For the second one in the code, it is needed to be checked if all work after merging in the pipeline.
> [todo] removal of two outdated TODOs

- .buildkite/claim-settlements.yml
A small fix on managing processed json to claim. The error caused the slack notification not providing data about processed epochs.
> [buildkite] fix claim settlement

- settlement-pipelines/src/stake_accounts.rs
Changing the claiming order of stake accounts for institutional staking.
I was considering to proceed with some CLI argument but then ended with using the same strategy as for liquid staking. Let's see if it is considered feasible.
> [settlement-pipelines][GEN-1260] claim for institutional with different priority

- .buildkite/collect-bonds.yml
- .buildkite/verify-settlements.yml
I found a couple of issues around buildkite pipelines (e.g. verify settlement check is handled by `check_command_execution_status`, not by a special if clause)
> [buildkite] fix for verify settlement to pass [GEN-1335]

- .buildkite/claim-settlements.yml
- .buildkite/close-settlements.yml
- .buildkite/fund-settlements.yml
- .buildkite/init-settlements.yml
- .buildkite/verify-settlements.yml
I need to disable redacted vars handling in other places for bonds as well. They cause the pipeline to fail which is more than annoying.
> [pipelines] empty redacted vars at all places

- .buildkite/claim-settlements.yml
- .buildkite/close-settlements.yml
- .buildkite/collect-bonds.yml
- .buildkite/fund-settlements.yml
- .buildkite/init-settlements.yml
- .buildkite/verify-settlements.yml
- packages/validator-bonds-cli-core/src/commands/mainCommand.ts
A change to not work with parameters of RPC_URL as a CLI command line argument, as the RPC URL contains a secret token. Using env var to be passed into CLI (Rust provides this, for TS adding such an option)
> [pipeline] not using rpc url as parameter

- CHANGELOG.md
- packages/validator-bonds-cli-core/package.json
- packages/validator-bonds-cli-core/src/commands/manage/configureBond.ts
- packages/validator-bonds-cli-core/src/commands/manage/initBond.ts
- packages/validator-bonds-cli-institutional/README.md
- packages/validator-bonds-cli-institutional/__tests__/test-validator/configureBondInstitutional.spec.ts
- packages/validator-bonds-cli-institutional/__tests__/test-validator/initBondInstitutional.spec.ts
- packages/validator-bonds-cli-institutional/package.json
- packages/validator-bonds-cli-institutional/src/index.ts
- packages/validator-bonds-cli/README.md
- packages/validator-bonds-cli/package.json
- packages/validator-bonds-cli/src/commands/manage/configureBond.ts
- packages/validator-bonds-cli/src/commands/manage/initBond.ts
- packages/validator-bonds-cli/src/index.ts
- packages/validator-bonds-sdk/package.json
The institutional CLI provides a way to configure `--cpmpe` that is relevant only for bidding and for institutional calculation.
> No cpmpe in institutional cli

- settlement-pipelines/__tests__/test-validator/pipelineSettlement.spec.ts
- settlement-pipelines/src/json_data.rs
- settlement-pipelines/src/reporting.rs
Fixing tests running a kind of integration test on pipeline settlement creation.
This test case takes time (~10 mins), and it is skipped by default. It was failing for a while, and with recent changes and fixes at #213, fixing the test processing as well.
NOTE: This PR is better to be reviewed after #213 is merged
> Fix pipeline settlement test [GEN-4612]

- packages/validator-bonds-cli-institutional/README.md
There is a mistake in CLI instructions. Readme says 1 SOL for every 10,000 staked. But it is 1 SOL for every 1000.
> [readme] update institutional readme as it is 1 sol for 1000 staked

- README.md
- api/src/repositories/bond.rs
This fixes an API issue caused by an incorrect filter applied to bond data processing, introduced with institutional staking.
The issue occurs because both bond types are not updated at the same time.
- Institutional bonds are created slightly later in the epoch compared to bidding bonds. As a result, the epoch for institutional bonds is effectively one epoch behind when compared to bidding bond data near the epoch boundary.
With the current SQL logic, the API breaks and returns no data (which causes the dashboard to fail), because the generic `cluster.epoch` value is taken from the highest epoch without filtering by bond type.
> [api] fixing bonds query to not fail on bond type limit [GEN-4939]

- .buildkite/prepare-institutional-distribution.yml
- Cargo.lock
- Cargo.toml
- settlement-distributions/institutional-distribution/src/custom_deserialize.rs
- settlement-distributions/institutional-distribution/src/institutional_payouts.rs
- settlement-distributions/institutional-distribution/src/lib.rs
There happens to be a big decimal numbers or small in scientific notation generated by TS Decimal.
This adds a custom deserializer that manages it and workarounds it.
```
Error: Failure at '--institutional-payouts ./institutional-payouts.json': invalid value: string "4.8076269033743718234e+882", expected a Decimal type representing a fixed-point number at line 11110 column 41
```
> [GEN-4975] workaround big decimal from institutional payouts

- .buildkite/prepare-institutional-distribution.yml
- scripts/generate-select-validator-report.bash
- scripts/settlement-json-listing.sh
A way to list the data within the payouts JSON, and whether it is reasonable to process it on-chain. I've got to this processing bash that lists data about payouts. This could need some tuning in the future, but having this as a start seems okayish.
Example listing: https://buildkite.com/marinade-finance/prepare-institutional-distribution/builds/64#0196fc5c-1122-42a8-a4d1-39e9e5b72f85
+ fixing an issue in PSR listing data for settlements in the initial settlement pipeline that shows the wrong info
> More info on institutional pipeline [GEN-5100][GEN-4883]

- Cargo.lock
- Cargo.toml
- settlement-config.yaml
- settlement-distributions/bid-psr-distribution/Cargo.toml
- settlement-distributions/bid-psr-distribution/src/protected_events.rs
- settlement-distributions/bid-psr-distribution/src/settlement_config.rs
- settlement-distributions/bid-psr-distribution/src/settlement_generator.rs
- settlement-distributions/bid-psr-distribution/src/utils.rs
Implements a CommissionRugPenalty, as described in the related documents on notion...
The task is here: https://www.notion.so/marinade/P-II-a-Implement-CommissionRugPenalty-into-validator-bonds-217e465715a48003959bdacc980a1b75?source=copy_link
An excerpt follows...
How is the CommissionRugPenalty penalty calculated?
The commission change settlement will increase by 10% for changes until 7% commission and an additional 90% for changes resulting in commission above 7%. For example, if a validator increases their commission by 2% from 5% to 7% they will pay 110% of the lost rewards. If they increase from 0% to 100%, they will pay 200% of the lost rewards. This approach allows honest validators to make commission adjustments while deterring commission rugs.
> [GEN-5372] Implement commission settlemen penalty markup

- CHANGELOG.md
- packages/validator-bonds-cli-core/package.json
- packages/validator-bonds-cli-core/src/utils.ts
- packages/validator-bonds-cli-institutional/README.md
- packages/validator-bonds-cli-institutional/package.json
- packages/validator-bonds-cli-institutional/src/index.ts
- packages/validator-bonds-cli/README.md
- packages/validator-bonds-cli/__tests__/test-validator/show.spec.ts
- packages/validator-bonds-cli/package.json
- packages/validator-bonds-cli/src/index.ts
- packages/validator-bonds-sdk/package.json
- packages/validator-bonds-sdk/src/web3.js/voteAccount.ts
Making it possible to use the validator identity to show the bond account
> CLI: permit validator identity to be used when showing bond info [GEN-6189]

- package.json
With pnpm 9+ (?) there is a need to approve build script to be processed from 3rd party dependencies. Allowing them for the repository.
> [pnpm] approve build scripts of bigint-buffer, bufferutil, node-hid, utf-8-validate [trivial]

- settlement-pipelines/src/bin/init_settlement.rs
When there are no settlements, then init fails. This happens normally, time to time for PSR where no PSR event in epoch has happened. This change makes the process no settlement initiated without an error.
> [pipeline] init: no merkle tree no error
